# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 404e2a1ffd37a14ee8e2834e6d0d3d1d4d75953f686fa3e9ff6338dfaefc57b00b7f43031e6e7aed9e4f153bcab2d3f7cbd3c39486e2897c01652be732a6779c

test:
  secret_key_base: 1de8f2314d0b46357c47fc0da0c0b6501ab8044d7f0f4af7469d7389046831f35ee4c0dcce7fa6bc8b4fa0f7e14b2dad9641b35ae96d769b62ff75e84672d73b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
